version: 2
updates:
- package-ecosystem: npm
  directory: "/Akismet"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vue
    versions:
    - "> 1.0.28"
  - dependency-name: vue
    versions:
    - ">= 2.a, < 3"
